### ISSUE TITLE
After adding a new certificate, pressing enter on the next modal does not close it

### ISSUE THREAD

**Issue by Keysox** [gitgoyle/mcsTraQue#3]
Steps to reproduce:

1. Click the "add" button from the "Certificates Entered" section.
2. After clicking "submit", the user is brought to a modal saying it has been saved.
3. Pressing "enter" creates a new certificate instead of closing the new dialog.

It would be nice to move focus to the "Close" button on this dialog, so it's easier to dismiss or allow the user to press "escape".

**Comment by gitgoyle** [comment]
after saving a modal dialog appears which says the event has been saved.
on show of the modal dialog the 'close' button gets focus.
if you press enter the close button is triggered since it has focus
if you press esc the close button is also triggered which will close the dialog.
