### ISSUE TITLE
Creating a new certificate with the datepicker; escape closes the wrong dialog

### ISSUE THREAD

**Issue by Keysox** [gitgoyle/mcsTraQue#4]
Steps to reproduce:

1. Click "add" under the "Certificates Entered" section
2. Open the date picker via the "Renewal Date" section
3. Press escape and notice how the modal closes instead of the date picker

See screenshot:
<img width="803" alt="screen shot 2016-11-13 at 11 52 55 am" src="https://cloud.githubusercontent.com/assets/6796642/20248000/3cee152c-a998-11e6-8fd6-cbfe7a0c931d.png">

**Comment by gitgoyle** [comment]
thanks for the emails, I'll look into those issues.  which browser are you
using, safari?

**Comment by Keysox** [comment]
So far, I've mainly been testing on Chrome.

**Comment by gitgoyle** [comment]
trapping the escape key press when the add modal dialog is open.  esc should no longer close the dialog, then only way to close is with the close button or the 'x' in the upper right corner of the header
